### ISSUE TITLE
混淆之后有错误

### ISSUE THREAD

**Issue by df13954** [ssseasonnn/Bracer#2]
java.lang.IllegalStateException: Incomplete hierarchy for class ArticleDetailActivity, unresolved classes [ch.ielse.view.imagewatcher.ImageWatcher.OnPictureLongPressListener, ch.ielse.view.imagewatcher.ImageWatcher.Loader, com.scwang.smart.refresh.layout.listener.OnRefreshListener, com.scwang.smart.refresh.layout.listener.OnLoadMoreListener]
        at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeErrorReporter.reportIncompleteHierarchy(RuntimeErrorReporter.kt:26)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassTypeConstructor.computeSupertypes(DeserializedClassDescriptor.kt:188)
        at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:80)
        at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:26)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:352)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:408)
        at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:27)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getNonDeclaredVariableNames(DeserializedClassDescriptor.kt:296)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(DeserializedMemberScope.kt:77)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(DeserializedMemberScope.kt:40)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:352)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:408)
        at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNamesLazy(Unknown Source:7)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNames(DeserializedMemberScope.kt:85)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedVariables(DeserializedMemberScope.kt:164)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedVariables(DeserializedClassDescriptor.kt:236)
        at kotlin.reflect.jvm.internal.KClassImpl.getProperties(KClassImpl.kt:204)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findPropertyDescriptor(KDeclarationContainerImpl.kt:109)
        at kotlin.reflect.jvm.internal.KPropertyImpl$_descriptor$1.invoke(KPropertyImpl.kt:102)
        at kotlin.reflect.jvm.internal.KPropertyImpl$_descriptor$1.invoke(KPropertyImpl.kt:27)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.KPropertyImpl.getDescriptor(KPropertyImpl.kt:105)
        at kotlin.reflect.jvm.internal.KPropertyImpl.getDescriptor(KPropertyImpl.kt:27)
        at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1.invoke(KCallableImpl.kt:74)
        at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1.invoke(KCallableImpl.kt:21)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.KCallableImpl.getReturnType(KCallableImpl.kt:80)
        at zlc.season.bracer.e.b(Util.kt:447)
        at zlc.season.bracer.a.a(ActivityParams.kt:38)

E/AndroidRuntime:     at com.android.debug.ui.fragment.HomeFragment.onItemClick(HomeFragment.kt:132)

            ArticleDetailActivity().apply {
                mArticleId = article.id  ：132
                recommendArticle = article
            }.start(this)

**Comment by ssseasonnn** [comment]
添加混淆配置：
```kotlin
-keepclassmembers @kotlin.Metadata class * {
    <methods>;
}
```

**Comment by ssseasonnn** [comment]
如果你有自定义的数据类型，也要keep住，如你上面的article类，简单的办法是让它实现Serializable接口，然后keep所有实现了Serializable的类：
```kotlin
-keep class * implements java.io.Serializable { *; }
```

**Comment by df13954** [comment]
bean的类型都keep了，增加了上面混淆配置，还是上面的错误。。...

**Comment by df13954** [comment]
`-dontobfuscate`
再增加这个，就ok啦~
